version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: discord
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - discord-music

  discord-music:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discord-music
    restart: always

    environment:
      - NODE_ENV=production
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_DEVELOPMENT_GUILD_ID=${DISCORD_DEVELOPMENT_GUILD_ID}
      - DATABASE_URL=postgresql://postgres:123456@postgres:5432/discord
    ports:
      - '4200:4200'
    volumes:
      - /app/node_modules

    networks:
      - discord-music

volumes:
  postgres_data:

networks:
  discord-music:
