export enum ICONS {
  PLAY = '▶️',
  PAUSE = '⏸️',
  STOP = '⏹️',
  NEXT = '⏭️',
  PREV = '⏮️',
  BACK = '◀️',
  LOOP = '🔀',
  SHUFFLE = '🔀',
  REFRESH = '🔄',
  ADD = '➕',
  DELETE = '🗑️',
  HEADPHONES = '🎧',
  LOADING = '⌛',
  SUCCESS = '✅',
  ERROR = '❌',
  ID = '🆔',
  WARNING = '⚠️',
  TRACK = '🎹',
  PLAYLIST = '🎵',
  QUEUE = '📜',
  FAVORITE = '⭐',
  ROBOT = '🤖',
  DISK = '💿',
}
